# Generated by Django 4.1.5 on 2023-01-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_auto_20230120_1042"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
